# Generated by Django 4.2.1 on 2023-06-02 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [

    ]
