# Generated by Django 4.2.1 on 2023-06-02 09:58

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    Pet = apps.get_model('pets', 'Pet')

    pets = Pet.objects.all()

    for pet in pets:
        pet.slug = slugify(f'{pet.pk} {pet.name}')

    Pet.objects.bulk_update(pets, ['slug'])


def remove_slugs(apps, schema_editor):
    Pet = apps.get_model('pets', 'Pet')

    pets = Pet.objects.all()

    for pet in pets:
        pet.slug = None

    Pet.objects.bulk_update(pets, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, remove_slugs)
    ]
